// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, feed_id, title, url, description, published_at, created_at, updated_at)
VALUES(
    DEFAULT,
    $1,
    $2,
    $3,
    $4,
    $5,
    DEFAULT,
    DEFAULT
)
RETURNING id, feed_id, title, url, description, published_at, created_at, updated_at
`

type CreatePostParams struct {
	FeedID      int32
	Title       string
	Url         string
	Description string
	PublishedAt time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.FeedID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostFromUser = `-- name: GetPostFromUser :many
SELECT p.id, p.feed_id, p.title, p.url, p.description, p.published_at, p.created_at, p.updated_at
FROM posts p
INNER JOIN feed_follows ff
ON ff.feed_id = p.feed_id
WHERE ff.user_id = $1
ORDER BY published_at DESC
LIMIT $2
`

type GetPostFromUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetPostFromUser(ctx context.Context, arg GetPostFromUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostFromUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
